<?php
return [
    'discovery_url' => '{{eureka_client_serviceUrl_defaultZone}}',
    'elastic_url' => '{{environments_ELASTIC_URL}}',
    'elastic_budgets_index' => '{{environments_ELASTIC_BUDGETS_INDEX}}',
    'elastic_tenders_index' => '{{environments_ELASTIC_TENDERS_INDEX}}',
    'elastic_plans_index' => '{{environments_ELASTIC_PLANS_INDEX}}',
    'elastic_contracts_index' => '{{environments_ELASTIC_CONTRACTS_INDEX}}',
    'elastic_cpv_index' => '{{environments_ELASTIC_CPV_INDEX}}',
    'elastic_budgets_type' => '{{environments_ELASTIC_BUDGETS_TYPE}}',
    'elastic_tenders_type' => '{{environments_ELASTIC_TENDERS_TYPE}}',
    'elastic_plans_type' => '{{environments_ELASTIC_PLANS_TYPE}}',
    'elastic_contracts_type' => '{{environments_ELASTIC_CONTRACTS_TYPE}}',
    'elastic_proceedings_index' => '{{environments_ELASTIC_PROCEEDINGS_INDEX}}',
    'elastic_proceedings_type' => '{{environments_ELASTIC_PROCEEDINGS_TYPE}}',
    'elastic_complaints_index' => '{{environments_ELASTIC_COMPLAINTS_INDEX}}',
    'elastic_complaints_type' => '{{environments_ELASTIC_COMPLAINTS_TYPE}}',
    'elastic_decisions_index' => '{{environments_ELASTIC_DECISIONS_INDEX}}',
    'elastic_decisions_type' => '{{environments_ELASTIC_DECISIONS_TYPE}}',
    'elastic_cpv_type' => '{{environments_ELASTIC_CPV_TYPE}}',
    'elastic_page_size' => '{{environments_ELASTIC_PAGE_SIZE}}',
    'sleep_error_interval' => '{{environments_SLEEP_ERROR_INTERVAL}}',
];
